import type { Vehicle } from "./types";

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "hilux-2021-cd-srv",
    name: "2021 Toyota Hilux Cd Srv",
    year: 2021,
    mileage: "77.800 Kms",
    priceARS: "$39.800.000 ARS",
    priceUSD: "US$ 39.800",
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format",
    location: "SAN FERNANDO, G.B.A. NORTE",
    details: [
      "Acepta permuta",
      "Acepta financiación",
      "Garantía mecánica",
      "Garantía de fábrica",
    ],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Toyota", type: "string" },
          { label: "Modelo", value: "Hilux", type: "string" },
          { label: "Versión", value: "Cd Srv 177cv", type: "string" },
          { label: "Tipo de vehículo", value: "Pickup", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Diésel", type: "string" },
          { label: "País de origen", value: "Alemania", type: "string" },
          { label: "Color", value: "Blanco", type: "string" },
          {
            label: "Dueños anteriores",
            value: 0,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Hidráulica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x2", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 2.8, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Manual", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 177,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          { label: "Aceleración", value: "No especifica", type: "string" },
          {
            label: "Válvulas por cilindro",
            value: 2,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "No especifica", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "5260 mm x 1850 mm x 1855 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.860 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 4, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 80,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 13.9,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 5.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 250,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "hilux-2017-cd-srx",
    name: "2017 Toyota Hilux Cd Srx",
    year: 2017,
    mileage: "221.000 Kms",
    priceARS: "$36.900.000 ARS",
    priceUSD: "US$ 36.900",
    image:
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: [
      "Acepta permuta",
      "Acepta financiación",
      "Garantía mecánica",
      "No garantía de fábrica",
    ],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Toyota", type: "string" },
          { label: "Modelo", value: "Hilux", type: "string" },
          { label: "Versión", value: "Cd Srv 177cv", type: "string" },
          { label: "Tipo de vehículo", value: "Pickup", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Diésel", type: "string" },
          { label: "País de origen", value: "Alemania", type: "string" },
          { label: "Color", value: "Gris", type: "string" },
          {
            label: "Dueños anteriores",
            value: 1,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Hidráulica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x4", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 2.8, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Automática", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 4941,
            type: "number",
            unit: "cm³",
            highlightRule: "max",
          },
          {
            label: "Potencia",
            value: 177,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Aceleración", value: "No especifica", type: "string" },
          {
            label: "Válvulas por cilindro",
            value: 2,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "Ácido en gel", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "5260 mm x 1850 mm x 1855 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.860 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 4, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 80,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 13.9,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 5.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 250,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "hilux-2019-cd-srx",
    name: "2019 Toyota Hilux Cd Srx",
    year: 2019,
    mileage: "174.000 Kms",
    priceARS: "$37.500.000 ARS",
    priceUSD: "US$ 37.500",
    image:
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: [
      "No acepta permuta",
      "No acepta financiación",
      "Sin garantía mecánica",
      "Garantía de fábrica",
    ],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Toyota", type: "string" },
          { label: "Modelo", value: "Hilux", type: "string" },
          { label: "Versión", value: "Cd Srv 177cv", type: "string" },
          { label: "Tipo de vehículo", value: "Pickup", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Diésel", type: "string" },
          { label: "País de origen", value: "Alemania", type: "string" },
          { label: "Color", value: "Rojo", type: "string" },
          {
            label: "Dueños anteriores",
            value: 2,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Hidráulica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x2", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 2.8, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Automática", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 177,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          { label: "Aceleración", value: "No especifica", type: "string" },
          {
            label: "Válvulas por cilindro",
            value: 2,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "No especifica", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "5260 mm x 1850 mm x 1855 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.860 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 4, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 80,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 13.9,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 5.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 250,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "golf-highline-2018",
    name: "2018 Volkswagen Golf Highline Tsi Dsg",
    year: 2018,
    mileage: "88.000 Kms",
    priceARS: "$20.000.000 ARS",
    priceUSD: "US$ 20.000",
    image:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: ["Acepta financiación", "Hoy por Modena Automotores"],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Volkswagen", type: "string" },
          { label: "Modelo", value: "Golf", type: "string" },
          { label: "Versión", value: "Highline Tsi Dsg", type: "string" },
          { label: "Tipo de vehículo", value: "Hatchback", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Nafta", type: "string" },
          { label: "País de origen", value: "Alemania", type: "string" },
          { label: "Color", value: "Negro", type: "string" },
          {
            label: "Dueños anteriores",
            value: 1,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Eléctrica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x2", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 1.4, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Automática (DSG)", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 150,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          {
            label: "Aceleración",
            value: 8.2,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Válvulas por cilindro",
            value: 4,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "Litio", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "4258 mm x 1452 mm x 1799 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.637 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 5, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 50,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 5.4,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 8.2,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 216,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "hilux-2016-cd-srx",
    name: "2016 Toyota Hilux Cd Srx",
    year: 2016,
    mileage: "109.000 Kms",
    priceARS: "$33.200.000 ARS",
    priceUSD: "US$ 33.200",
    image:
      "https://images.unsplash.com/photo-1494976688153-ca3ce29d8df4?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: ["Acepta permuta", "Acepta financiación", "Hace 2 días"],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Toyota", type: "string" },
          { label: "Modelo", value: "Hilux", type: "string" },
          { label: "Versión", value: "Cd Srx", type: "string" },
          { label: "Tipo de vehículo", value: "Pickup", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Diésel", type: "string" },
          { label: "País de origen", value: "Japón", type: "string" },
          { label: "Color", value: "Rojo", type: "string" },
          {
            label: "Dueños anteriores",
            value: 1,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Hidráulica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x4", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 2.8, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Automática", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 177,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          { label: "Aceleración", value: "No especifica", type: "string" },
          {
            label: "Válvulas por cilindro",
            value: 2,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "No especifica", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "5260 mm x 1850 mm x 1855 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.860 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 4, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 80,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 13.9,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 5.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 250,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "golf-2010-highline",
    name: "2010 Volkswagen Golf Highline",
    year: 2010,
    mileage: "90.000 Kms",
    priceARS: "$6.900.000 ARS",
    priceUSD: "US$ 6.900",
    image:
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: ["Acepta permuta", "Acepta financiación"],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "Volkswagen", type: "string" },
          { label: "Modelo", value: "Golf", type: "string" },
          { label: "Versión", value: "Highline", type: "string" },
          { label: "Tipo de vehículo", value: "Hatchback", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Nafta", type: "string" },
          { label: "País de origen", value: "Alemania", type: "string" },
          { label: "Color", value: "Gris", type: "string" },
          {
            label: "Dueños anteriores",
            value: 2,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Asistida", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x2", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 1.6, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Manual", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 102,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          {
            label: "Aceleración",
            value: 11.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Válvulas por cilindro",
            value: 2,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "Plomo-ácido", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "4204 mm x 1479 mm x 1759 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.578 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 5, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 55,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 7.1,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 11.3,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 188,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
  {
    id: "ds3-crossback-2021",
    name: "2021 D.S. DS3 Crossback Puretech So Chic",
    year: 2021,
    mileage: "82.000 Kms",
    priceARS: "$26.500.000 ARS",
    priceUSD: "US$ 26.500",
    image:
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&h=300&fit=crop&auto=format",
    location: "VILLA LUGANO, CABA.",
    details: ["Acepta financiación", "Hoy por Autos al Río"],
    categories: [
      {
        title: "General",
        attributes: [
          { label: "Marca", value: "D.S.", type: "string" },
          { label: "Modelo", value: "DS3 Crossback", type: "string" },
          { label: "Versión", value: "Puretech So Chic", type: "string" },
          { label: "Tipo de vehículo", value: "SUV", type: "string" },
          { label: "Condición", value: "Usado", type: "string" },
          { label: "Combustible", value: "Nafta", type: "string" },
          { label: "País de origen", value: "Francia", type: "string" },
          { label: "Color", value: "Blanco", type: "string" },
          {
            label: "Dueños anteriores",
            value: 1,
            type: "number",
            highlightRule: "min",
          },
          { label: "Dirección", value: "Eléctrica", type: "string" },
        ],
      },
      {
        title: "Seguridad",
        attributes: [
          {
            label: "Faros con regulación automática",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Faros antinieblas traseros",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Airbag",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Control de estabilidad",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          { label: "Control de tracción", value: "4x2", type: "string" },
          {
            label: "Frenos ABS",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cierre centralizado de puertas",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Tercera luz de freno LED",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
      {
        title: "Prestaciones y mecánica",
        attributes: [
          { label: "Motor", value: 1.2, type: "number", highlightRule: "max" },
          { label: "Transmisión", value: "Automática", type: "string" },
          {
            label: "Defensa delantera",
            value: "No especifica",
            type: "string",
          },
          {
            label: "Cilindrada",
            value: 130,
            type: "number",
            unit: "hp",
            highlightRule: "max",
          },
          { label: "Potencia", value: "No especifica", type: "string" },
          {
            label: "Aceleración",
            value: 9.2,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Válvulas por cilindro",
            value: 3,
            type: "number",
            highlightRule: "max",
          },
          { label: "Tipo de batería", value: "Litio", type: "string" },
        ],
      },
      {
        title: "Rendimiento y dimensiones",
        attributes: [
          {
            label: "Largo x Alto x Ancho",
            value: "4118 mm x 1534 mm x 1791 mm",
            type: "dimension",
          },
          {
            label: "Distancia entre ejes",
            value: "2.558 mm",
            type: "dimension",
          },
          { label: "Asientos", value: 5, type: "number", highlightRule: "max" },
          { label: "Puertas", value: 5, type: "number", highlightRule: "max" },
          {
            label: "Capacidad del tanque",
            value: 44,
            type: "number",
            unit: "L",
            highlightRule: "max",
          },
          {
            label: "Consumo medio",
            value: 5.5,
            type: "number",
            unit: "l/100 km",
            highlightRule: "min",
          },
          {
            label: "Aceleración",
            value: 9.2,
            type: "number",
            unit: "segundos",
            highlightRule: "min",
          },
          {
            label: "Velocidad máx.",
            value: 196,
            type: "number",
            unit: "km/h",
            highlightRule: "max",
          },
        ],
      },
      {
        title: "Equipamiento destacado",
        attributes: [
          {
            label: "Cámara de Retroceso",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "MP3",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Alarma",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Llantas de Aleación",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Bluetooth",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Radio AM/FM",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "DVD",
            value: false,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Posa Vasos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cargador USB",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Computadora de Abordo",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Piloto Automático",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Aire Acondicionado",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Cristales Eléctricos",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
          {
            label: "Desempañador trasero",
            value: true,
            type: "boolean",
            highlightRule: "boolean",
          },
        ],
      },
    ],
  },
];
